In [1]:
import cvxpy as cvx
import numpy as np

In [81]:
A = np.array([[1,2],[1,-4],[5,76]])
u1 = -2
u2 = -3
b = np.array([u1,u2,1])
b = b.reshape(3,1)
Q = np.array([[1 , -0.5] , [-0.5 , 2]])
f = np.array([-1,0])


In [83]:
# solve the problem
x = cvx.Variable([2,1])
problem_formoulation = cvx.quad_form(x, Q) + x.T@f
constraints = [A@x <= b]
min_value = cvx.Problem(cvx.Minimize(problem_formoulation), constraints).solve()
landas = constraints[0].dual_value
x_val = np.array(x.value)
x_val =x_val.reshape(2,1)

print("The minimum value is: ")
print (min_value)
print("the minimum point is: ")
print (x.value)
print("The Lagrange multipliers are: ")
print (landas)

# check kkt conditions
very_min = 0.000000000000006

# shart 1 kkt
print("barresi shart aval kkt :")
print((A.dot(x_val)-b).all()<very_min)

# shart 2 kkt
print("barresi shart dovom kkt :")
print(landas.all()>=0)

# shart 3 kkt
kk3 = landas*(A.dot(x_val)-b)
print("barresi shart sevom kkt :")
print(kk3.all()<very_min and kk3.all()>-very_min)

# shart 4 kkt
print("barresi shart chaharom kkt :")
kk4 = (2*Q.dot(x_val)) + f.T + (A.transpose().dot(constraints[0].dual_value))
print (kk4.all()<very_min and kk4.all()>-very_min)

The minimum value is: 
8.222222222222221
the minimum point is: 
[[-2.33333333]
 [ 0.16666667]]
The Lagrange multipliers are: 
[[2.74774125]
 [2.88523345]
 [0.04007173]]
barresi shart aval kkt :
True
barresi shart dovom kkt :
True
barresi shart sevom kkt :
True
barresi shart chaharom kkt :
True


In [88]:
output = np.zeros((9, 4))
error = np.array([-0.05, 0,0.05])

c = 0
for i in error:
    for j in error:
        b_new = b+np.array(np.array([i,j,0])).T
        p_pred = min_value - (landas[0]*i + landas[1]*j)
        constraints = [A@x <= b_new]
        p_exact = cvx.Problem(cvx.Minimize(problem_formoulation), constraints).solve()
        output[c,:] = np.array([i, j, p_pred, p_exact])
        c += 1
print (output)

C:\Users\Scrum Master\AppData\Local\Temp\ipykernel_1904\409832979.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  output[c,:] = np.array([i, j, p_pred, p_exact])


[[-0.05       -0.05        8.50387096  8.51638889]
 [-0.05        0.          8.35960928  8.51638889]
 [-0.05        0.05        8.21534761  8.51638889]
 [ 0.         -0.05        8.36648389  8.51638889]
 [ 0.          0.          8.22222222  8.22222222]
 [ 0.          0.05        8.07796055  8.22222222]
 [ 0.05       -0.05        8.22909683  8.51638889]
 [ 0.05        0.          8.08483516  8.22222222]
 [ 0.05        0.05        7.94057349  8.22222222]]
