## Imports

In [24]:
import cvxpy as cvx
import numpy as np

## Defining Variables

In [25]:
A = np.array([[1,2],[1,-4],[5,76]])
u1 = -2
u2 = -3
b = np.array([u1,u2,1])
b = b.reshape(3,1)
Q = np.array([[1 , -0.5] , [-0.5 , 2]])
f = np.array([-1,0])


## Defining the CVX Problem

In [26]:
x = cvx.Variable([2,1])
formulation = cvx.quad_form(x, Q) + x.T@f
constraints = [A@x <= b]
problem = cvx.Problem(cvx.Minimize(formulation), constraints)


## Solving the problem

In [27]:
min_value = problem.solve()
lambdas = constraints[0].dual_value
x_val = np.array(x.value)
x_val = x_val.reshape(2,1)

print("Min Value:")
print (min_value, "\n")

print("Min Point:")
print (x.value, "\n")

print("The Lagrange Multipliers:")
print (lambdas)


Min Value:
8.222222222222221 

Min Point:
[[-2.33333333]
 [ 0.16666667]] 

The Lagrange Multipliers:
[[2.74774125]
 [2.88523345]
 [0.04007173]]


## KKT Conditions

In [28]:
# check kkt conditions
epsilon = 0.000000000000001

# KKT Cond 1
print("# KKT Cond 1 : ", end="")
print((A.dot(x_val)-b).all()<epsilon)

# KKT Cond 2
print("# KKT Cond 2 : ", end="")
print(lambdas.all()>=0)

# KKT Cond 3
kkt3 = lambdas*(A.dot(x_val)-b)
print("# KKT Cond 3 : ", end="")
print(kkt3.all()<epsilon and kkt3.all()>-epsilon)

# KKT Cond 4
print("# KKT Cond 4 : ", end="")
kkt4 = (2*Q.dot(x_val)) + f.T + (A.transpose().dot(constraints[0].dual_value))
print (kkt4.all()<epsilon and kkt4.all()>-epsilon)

# KKT Cond 1 : True
# KKT Cond 2 : True
# KKT Cond 3 : True
# KKT Cond 4 : True


In [43]:
output = np.zeros((9, 4))
error = np.array([-0.05, 0, 0.05])

c = 0
for i in error:
    for j in error:
        b_new = b+np.array(np.array([i,j,0])).T
        p_pred = min_value - (lambdas[0]*i + lambdas[1]*j)
        constraints = [A@x <= b_new]
        p_exact = cvx.Problem(cvx.Minimize(formulation), constraints).solve()
        output[c, 0] = i
        output[c, 1] = j
        output[c, 2] = p_pred
        output[c, 3] = p_exact
        c += 1
print(output)

[[-0.05       -0.05        8.50387096  8.51638889]
 [-0.05        0.          8.35960928  8.51638889]
 [-0.05        0.05        8.21534761  8.51638889]
 [ 0.         -0.05        8.36648389  8.51638889]
 [ 0.          0.          8.22222222  8.22222222]
 [ 0.          0.05        8.07796055  8.22222222]
 [ 0.05       -0.05        8.22909683  8.51638889]
 [ 0.05        0.          8.08483516  8.22222222]
 [ 0.05        0.05        7.94057349  8.22222222]]
